version: "3"

services:
  db:
    image: mysql:latest
    container_name: mmetering_mysql
    ports:
      - "3306:3306"
    env_file: ./mysql_conf.txt
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - main
  redis:
    image: "redis:alpine"
    restart: always
    container_name: mmetering_redis
    networks:
      - main
  web:
    build: .
    container_name: mmetering_django
    command: >
      bash -c "sleep 6 && python /mmetering-server/manage.py migrate --noinput
      && gunicorn mmetering_server.wsgi -b 0.0.0.0:8000 --workers 2"
    volumes:
      - .:/mmetering-server
      - /var/log/mmetering:/var/log/mmetering
      - ~/mmetering-data:/mmetering-data
      - /dev:/dev
      - static_volume:/mmetering-server/static
      - media_volume:/mmetering-server/media
    networks:
      - main
      - nginx
    links:
      - redis
    restart: on-failure:5
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - static_volume:/static
    - media_volume:/media
    ports:
    - "8000:80" # Runs nginx on port 8000
    networks:
      - nginx
    depends_on:
    - web
  celery:
    build: .
    container_name: mmetering_celery
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    command: celery -A mmetering_server worker -l info
    restart: on-failure:5
    volumes:
      - .:/mmetering-server
      - /dev/serial/by-id/:/dev/serial/by-id
    networks:
      - main
    links:
      - redis
    depends_on:
      - web
      - db
      - redis
  celery-beat:
    build: .
    container_name: mmetering_celery_beat
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    command: celery -A mmetering_server beat --pidfile= -l info
    restart: on-failure:5
    volumes:
      - .:/mmetering-server
      - /dev/serial/by-id/:/dev/serial/by-id
    networks:
      - main
    links:
      - redis
    depends_on:
      - web
      - db
      - redis
      - celery
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mmetering_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    networks:
      - main
    ports:
      - "8082:80"
    volumes:
      - /sessions

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  main:
    driver: bridge
  nginx:
    driver: bridge
