version: '3'

services:
  db:
    image: mysql
  web:
    build: .
    command: bash -c "python /mmetering_server/manage.py migrate --noinput && python /mmetering_server/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/mmetering_server
    ports:
      - "8000:8000"
    depends_on:
      - db
